bluebutton-devs:
  members:
  - johnfrenchxyz
  - cstrama-fearless
  - whytheplatypus
  - dtisza1
  channel: "#team-bluebutton"
  include_repos:
  - bluebutton-web-server
  - bluebutton-deployment
  use_labels: true
  exclude_labels:
  - WIP
