bluebutton-devs:
  members:
  - johnfrenchxyz
  - cstrama-fearless
  - whytheplatypus
  - dtisza1
  - jzulim
  channel: "#team-bluebutton"
  include_repos:
  - bluebutton-web-server
  - bluebutton-deployment
  - bluebutton-css
  - bluebutton-site-static
  use_labels: true
  exclude_labels:
  - WIP
