development-team:
  members:
  - bushong1
  - zander312
  - sigfriedjk
  - unblevable
  - averysmithproductions
  - cyber-decker
  - brooksa321
  channel:
    "#the-dojo"
  quotes:
  - I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking. And I plan on finding out what that is.
  - Where shall we go for lunch?
  - Where's the data?
  include_repos:
  - sba-gov-katana
  - sba-gov-daisho
  - sba-gov-wakazashi
  - sba-gov-chef
  - sba-gov-test
