sbagov-developers:
  members:
  - bushong1
  - zander312
  - sigfriedjk
  - unblevable
  - averysmithproductions
  - cyber-decker
  - brooksa321
  channel:
    "#sba-gov-pull-requests"
  include_repos:
  - sba-gov-katana
  - sba-gov-daisho
  - sba-gov-wakazashi
  - sba-gov-chef
  - sba-gov-test
  use_labels: true
  exclude_labels:
  - WIP
sbagov-devops:
  members:
  - bushong1
  - sigfriedjk
  - brooksa321
  - jsmigovsky
  channel:
    "#sba-gov-devops"
  include_repos:
  - sba-gov-infrastructure
  - sba-gov-containers
  use_labels: true
  exclude_labels:
  - WIP
hubzone:
  members:
  - solipet
  - tbolt
  - patkelsh
  - xcelldf
  - leeplace
  - jondandois
  - bushong1
  - jgsmith-usds
  channel:
    "#sba-hubzone"
  include_repos:
  - hubzone-data-etl
  - hubzone-testing
  - hubzone-webmap
  - hubzone-api
  - hubzone-report
  - hubzone-geoserver-config
  - shared-services-prototype
  - notification-api
  - message-api
  use_labels: true
  exclude_labels:
  - WIP

hubzone-devops:
  members:
  - bushong1
  - solipet
  - jgsmith-usds
  channel:
    "#sba-hubzone-devops"
  include_repos:
  - infrastructure
  - devops
  - cookbook-hzetl
  - cookbook-geoserver
  - cookbook-geoapi
  - cookbook-hzmap
  - cookbook-shared-activity
  - cookbook-shared-common
  - cookbook-hubzone-common
  - cookbook-hubzone-deploy
  - cookbook-hubzone-nginx
  - cookbook-shared-messaging
  - cookbook-shared-notification
  - cookbook-shared-deploy
  - cookbook-hubzone-report
  - hubzone-deploy
  - hubzone-packer
  - proofs-of-concept
  - aws-cft-tools
  use_labels: true
  exclude_labels:
  - WIP
