sbagov-developers:
  members:
  - sigfriedjk
  - unblevable
  - averysmithproductions
  - cyber-decker
  - brooksa321
  - lsemesky
  - KevL927
  - jrwatts
  - acmancuso
  channel: "#sba-gov-development"
  include_repos:
  - sba-gov-katana
  - sba-gov-daisho
  - sba-gov-wakizashi
  - sba-gov-scripts
  - sba-gov-content-api
  - sba-gov-size-standards-api
  - sba-gov-geocoder
  - sba-gov-bulk-uploader
  use_labels: true
  exclude_labels:
  - WIP
sbagov-devops:
  members:
  - bushong1
  - sigfriedjk
  - brooksa321
  - jsmigovsky
  - elijahmuha
  - rchillard-gov
  channel:
    "#team-wizards-of-ops"
  include_repos:
  - devops
  - nessus-packer
  - sba-app
  - sba-certificate-renewal
  - sba-gov-infrastructure
  - sba-gov-containers
  - sba-gov-chef
  - sba-gov-wordpress
  - sba-gov-nginx-proxy
  - sba-gov-efscopy
  - sba-gov-scripts
  - sba-gov-tanto
  - sba-gov-wakizashi
  - sba-gov-packer
  - sba-gov-packer-files
  - hubzone-landing
  use_labels: true
  exclude_labels:
  - WIP
hubzone:
  members:
  - solipet
  - jennywagg
  - tbolt
  - jondandois
  - PatKelsh
  - jtsengatfearsol
  - xcelldf
  - leeplace
  - sseabrease
  - bushong1
  - jsmigovsky
  - jgsmith-usds
  channel: "#team-sba-certify"
  include_repos:
  - hubzone-api
  - hubzone-data-etl
  - hubzone-geoserver-config
  - hubzone-report
  - hubzone-scripts
  - hubzone-testing
  - hubzone-webmap
  - shared-services-prototype
  - hubzone-landing
  - certify-application-overview
  - message-api
  - notification-api
  - activity-api
  - sba-idp
  - omniauth-sba-idp
  - business-profile-api
  - doc-api
  - email-api
  - program-api
  - certify_messages
  - certify_notifications
  - certify_activity_log
  - certify_user
  - certify_business
  - certify_documents
  - certify_email
  - certify_programs
  use_labels: true
  exclude_labels:
  - WIP

hubzone-devops:
  members:
  - bushong1
  - solipet
  - jgsmith-usds
  - jsmigovsky
  channel: "#sba-hubzone-devops"
  include_repos:
  - infrastructure
  - devops
  - cookbook-hzetl
  - cookbook-geoserver
  - cookbook-geoapi
  - cookbook-hzmap
  - cookbook-shared-activity
  - cookbook-shared-common
  - cookbook-hubzone-common
  - cookbook-hubzone-deploy
  - cookbook-hubzone-nginx
  - cookbook-shared-messaging
  - cookbook-shared-notification
  - cookbook-shared-deploy
  - cookbook-hubzone-report
  - hubzone-deploy
  - hubzone-landing
  - hubzone-packer
  - proofs-of-concept
  - aws-cft-tools
  use_labels: true
  exclude_labels:
  - WIP
