sbagov-developers:
  members:
  - sigfriedjk
  - unblevable
  - averysmithproductions
  - cyber-decker
  - brooksa321
  - PatKelsh
  - amyd11
  - KevL927
  - jrwatts
  - acmancuso
  channel: "#sba-gov-development"
  include_repos:
  - sba-gov-katana
  - sba-gov-daisho
  - sba-gov-wakizashi
  - sba-gov-scripts
  - sba-gov-content-api
  - sba-gov-misc-api
  - sba-gov-size-standards-api
  - sba-gov-geocoder
  - sba-gov-bulk-uploader
  - sba-gov-integration-tests
  use_labels: true
  exclude_labels:
  - WIP
#sbagov-devops:
#  members:
#  - bushong1
#  - sigfriedjk
#  - brooksa321
#  - jsmigovsky
#  - elijahmuha
#  - rchillard-gov
#  channel:
#    "#team-wizards-of-ops"
#  include_repos:
#  - bitwarden-infrastructure
#  - devops
#  - hubzone-landing
#  - hubzone-packer
#  - nessus-packer
#  - oda-dlap-infrastructure
#  - oda-dlap-packer
#  - oda-dlap-web
#  - open-source
#  - sba-app
#  - sba-aws-helpers
#  - sba-certificate-renewal
#  - sba-eli-infrastructure
#  - sba-gov-chef
#  - sba-gov-ckan
#  - sba-gov-containers
#  - sba-gov-cypress
#  - sba-gov-efscopy
#  - sba-gov-infrastructure
#  - sba-gov-nginx-proxy
#  - sba-gov-packer
#  - sba-gov-packer-files
#  - sba-gov-scripts
#  - sba-gov-tanto
#  - sba-gov-wakizashi
#  - sba-gov-wordpress
#  - sba-management-infrastructure
#  - sba-security-infrastructure
#  - sbir-gov-data-extract
#  - sbir-gov-infrastructure
#  - sbir-gov-packer
#  - sbir-gov-website
#  - terraform-aws-backup-plans
#  - terraform-aws-bootstrapper
#  - terraform-aws-inspector
#  - terraform-aws-scheduled-lambda
#  - terraform-aws-sns-notification-framework
#  - terraform-aws-waf-global
#  - terraform-aws-waf-regional
#  - terraform-aws-account-config
#  - sba-fof-infrastructure
#  use_labels: true
#  exclude_labels:
#  - WIP
