sbagov-developers:
  members:
  - sigfriedjk
  - unblevable
  - averysmithproductions
  - cyber-decker
  - brooksa321
  - lsemesky
  - KevL927
  - jrwatts
  channel: "#sba-gov-development"
  include_repos:
  - sba-gov-katana
  - sba-gov-daisho
  - sba-gov-wakizashi
  - sba-gov-scripts
  - sba-gov-test
  - sba-gov-bulk-uploader
  use_labels: true
  exclude_labels:
  - WIP
sbagov-devops:
  members:
  - bushong1
  - sigfriedjk
  - brooksa321
  - jsmigovsky
  channel:
    "#team-hyan_rillards"
  include_repos:
  - sba-gov-infrastructure
  - sba-gov-containers
  - sba-gov-chef
  - sba-gov-wordpress
  - sba-gov-nginx-proxy
  - sba-gov-efscopy
  - sba-gov-scripts
  - sba-gov-tanto
  - sba-gov-wakizashi
  - sba-gov-packer
  - sba-gov-packer-files
  use_labels: true
  exclude_labels:
  - WIP
hubzone:
  members:
  - solipet
  - tbolt
  - patkelsh
  - xcelldf
  - leeplace
  - jondandois
  - bushong1
  - jgsmith-usds
  channel: "#sba-hubzone"
  include_repos:
  - hubzone-data-etl
  - hubzone-testing
  - hubzone-webmap
  - hubzone-api
  - hubzone-report
  - hubzone-geoserver-config
  - shared-services-prototype
  - notification-api
  - message-api
  - omniauth-sba-idp
  - sba-idp
  - business-profile-api
  - certify-sam-api
  use_labels: true
  exclude_labels:
  - WIP

hubzone-devops:
  members:
  - bushong1
  - solipet
  - jgsmith-usds
  channel: "#sba-hubzone-devops"
  include_repos:
  - infrastructure
  - devops
  - cookbook-hzetl
  - cookbook-geoserver
  - cookbook-geoapi
  - cookbook-hzmap
  - cookbook-shared-activity
  - cookbook-shared-common
  - cookbook-hubzone-common
  - cookbook-hubzone-deploy
  - cookbook-hubzone-nginx
  - cookbook-shared-messaging
  - cookbook-shared-notification
  - cookbook-shared-deploy
  - cookbook-hubzone-report
  - hubzone-deploy
  - hubzone-packer
  - proofs-of-concept
  - aws-cft-tools
  use_labels: true
  exclude_labels:
  - WIP
